// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Zu9vFAxpOeDQ6fESHeFU7KER2wsD_ec',
    appId: '1:567295874578:web:fd84c1c08c1f16242b6acb',
    messagingSenderId: '567295874578',
    projectId: 'paragram-c114d',
    authDomain: 'paragram-c114d.firebaseapp.com',
    storageBucket: 'paragram-c114d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwizyH0iVC9JAks1HH6pUSqY-S4_ENQ0',
    appId: '1:567295874578:android:e8a81b8afb9afaea2b6acb',
    messagingSenderId: '567295874578',
    projectId: 'paragram-c114d',
    storageBucket: 'paragram-c114d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTTd3StfB-nDPzDl9Y7azPO7c-zGDxHgg',
    appId: '1:567295874578:ios:a12119580bdfcc232b6acb',
    messagingSenderId: '567295874578',
    projectId: 'paragram-c114d',
    storageBucket: 'paragram-c114d.appspot.com',
    iosClientId: '567295874578-lpor2piho77vhb2qah3ud6vrpiiobd0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.paragram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTTd3StfB-nDPzDl9Y7azPO7c-zGDxHgg',
    appId: '1:567295874578:ios:a12119580bdfcc232b6acb',
    messagingSenderId: '567295874578',
    projectId: 'paragram-c114d',
    storageBucket: 'paragram-c114d.appspot.com',
    iosClientId: '567295874578-lpor2piho77vhb2qah3ud6vrpiiobd0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.paragram',
  );
}
